### PR TITLE
Add tests with both gccgo and gc

### PR DESCRIPTION
**Pull request by clausecker**
The first commit alters the Makefile to allow testing with different compilers, the second commit adds my own tests on a thinkpad T520.

### CODE REVIEW

**Comment by davecheney** [comment]
Hi,

Thanks for your contribution, this is great. Can you please also add a note to the README.md file explaining how to switch between gc and gccgo (and probably that people should do a `make clean` when they switch)

**Comment by clausecker** [comment]
I've added a notice. Running make clean is not needed (since the tool go makes a clear distinction between gc objects and gccgo objects) but it is adviceable to stash away the previous benchmarking results so you don't accidentially overwrite them.

**Comment by davecheney** [comment]
LGTM. Thank you. I've added you as a collaborator on this project, please feel free to merge this when you're happy with it.

**Comment by clausecker** [comment]
Thank you for this. I'm gonna merge it right now.

**Pull request merged**
