### PR TITLE
Benchmarks for time.Now and friends.

### PR DESCRIPTION
**Pull request by alberts**

### CODE REVIEW

**Comment by alberts** [comment]
Going to make a few more changes before we commit this, if you're happy with including these?

**Comment by davecheney** [comment]
SGTM.

**Comment by davecheney** [comment]
Hi Albert, is this ready for review ?

**Comment by alberts** [comment]
Coming soon. What's here now can also be merged and I'll refactor and add a few more benchmarks in the next few days.

**Comment by davecheney** [comment]
I've added you as a collaborator, please land this when ready.

Thanks!

**Pull request closed without merging**
